USER_LIBS = jlewallen L3G4200D/L3G4200D LSM303/LSM303 Arduino-PID-Library/PID_v1
SYSTEM_LIBS = Servo Wire Wire/utility
MON_SPEED = 115200
USER_C_FLAGS=-Wl,-u,vfprintf -lprintf_flt 
include ../Makefile.env
include ../Makefile.master
